---
# tasks file for primaria

- name: Gather /etc/centro
  command: cat /etc/centro
  register: centro

- name: Gather /etc/tipo
  command: cat /etc/tipo
  register: tipo

- name: Debug pkglist_primara
  debug:
    msg: "{{ pkglist_primaria }}"

- name: Install list of packages
  include_tasks: install_pkgs.yml
  loop: "{{ pkglist_primaria }}"

- name: Write release into a file
  copy:
    dest: "/etc/llx_primaria"
    content: |
      primaria

- name: debug vars
  debug:
    msg: "{{centro.stdout}} {{tipo.stdout}} \n"

- name: install if file contents /etc/centro is numero15
  copy:
    dest: "/tmp/es_asi"
    content: |
      jaja
  when: (centro is defined) and (tipo is defined) and ( centro.stdout == 'numero15') and ( tipo.stdout == 'secundaria')

- name: debug condition
  debug:
    msg: "has test_centro15 tag"
  when: test_centro15 is defined

- name: Mostrar tags con las que se ha llamado este rol
  debug:
    msg: "Este rol ha sido llamado con las siguientes tags: {{ ansible_run_tags | join(', ') }}"
  tags:
    - always
