---
# tasks file for primaria

- name: Gather /etc/centro
  command: cat /etc/centro
  register: centro

- name: Gather /etc/tipo
  command: cat /etc/tipo
  register: tipo

- name: Install list of packages
  include_tasks: install_pkgs.yml
  loop: "{{ pkglist_primaria }}"

- name: Write release into a file
  copy:
    dest: "/etc/llx_primaria"
    content: |
      primaria

- name: debug vars
  debug:
    msg: "{{centro}} {{tipo}} \n"

- name: install if file contents /etc/centro is numero15
  copy:
    dest: "/tmp/es_asi"
    content: |
      jaja
  when: (centro is defined) and (tipo is defined) and (centro == 'numero15') and (tipo == 'secundaria')
