---
- hosts: localhost
  tasks:
    - shell: uname -a
      register: uname
    - name: show uname
      debug: var=uname.stdout
    - shell: id
      register: id
    - name: show id
      debug: var=id.stdout
    

- hosts: all
  tasks:
    - shell: uname -a
      register: uname
    - name: debug uname
      debug: var=uname.stdout
    - shell: id
      register: id
    - name: show id
      debug: var=id.stdout

    - name: Gather /etc/centro
      command: cat /etc/centro
      register: centro_cmd
    - name: debug centro 15
      debug:
        msg: "centro {{ centro_cmd.stdout }}"

