---
- hosts: localhost
  pre_tasks:
    - name: Gather /etc/centro
      command: cat /etc/centro
      register: centro_cmd
  tasks:
    - shell: hostname
    - name: debug centro 15
      debug:
        msg: "centro {{ centro_cmd }}"