---
# tasks file for lliurex

- name: Gather lliurex version
  command: lliurex-version -n
  register: llx_version

- name: Gather lliurex flavour
  command: lliurex-version -f
  register: llx_flavour

- name: Gather /etc/school
  command: cat /etc/school
  register: centro_cmd

- name: Gather /etc/type
  command: cat /etc/type
  register: tipo_cmd

- name: Gather /etc/level
  command: cat /etc/level
  register: nivel_cmd

- name: Setup facts
  set_fact:
    llxversion: "{{ llx_version.stdout }}"
    llxflavour: "{{ llx_flavour.stdout }}"
    centro: "{{ centro_cmd.stdout }}"
    tipo: "{{ tipo_cmd.stdout }}"
    nivel: "{{ nivel_cmd.stdout }}"
